//==============================================================================
// Copyright (c) 2015-2017 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief THIS CODE WAS AUTOGENERATED BY PASSTHROUGHGENERATOR ON 01/31/17
//==============================================================================

#ifndef _HSADEBUGGERRTMODULEDECLS_H_
#define _HSADEBUGGERRTMODULEDECLS_H_

#include <amd_hsa_tools_interfaces.h>

typedef decltype(hsa_ext_tools_set_callback_functions)* hsa_ext_tools_set_callback_functions_fn_t;
typedef decltype(hsa_ext_tools_get_callback_functions)* hsa_ext_tools_get_callback_functions_fn_t;
typedef decltype(hsa_ext_tools_set_callback_arguments)* hsa_ext_tools_set_callback_arguments_fn_t;
typedef decltype(hsa_ext_tools_get_callback_arguments)* hsa_ext_tools_get_callback_arguments_fn_t;



#endif // _HSADEBUGGERRTMODULEDECLS_H_

